# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-08 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sva', '0002_auto_20180502_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='siape',
        ),
        migrations.AlterField(
            model_name='campus',
            name='cidade',
            field=models.CharField(choices=[('ARAXA', 'Araxá'), ('CURVELO', 'Curvelo'), ('TIMOTEO', 'Timóteo'), ('DIVINOPOLIS', 'Divinópolis'), ('NEPOMUCENO', 'Nepomuceno'), ('LEOPOLDINA', 'Leopoldina'), ('BELO HORIZONTE', 'Belo Horizonte'), ('VARGINHA', 'Varginha'), ('CONTAGEM', 'Contagem')], max_length=45),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel_ensino',
            field=models.IntegerField(choices=[(4, 'DOUTORADO'), (3, 'MESTRADO'), (2, 'GRADUACAO'), (1, 'TECNICO'), (5, 'ESPECIALIZACAO')], verbose_name='Nível de Ensino'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(6, 'Vaga de Interesse'), (3, 'Cadastro de Empresa'), (9, 'Resposta no Fórum'), (2, 'Cadastro de Professor'), (7, 'Solicitação de Área de Atuação'), (4, 'Cadastro de Vaga'), (1, 'Indicação de Vaga'), (5, 'Aprovação de Vaga'), (8, 'Nova Mensagem no Fórum')], verbose_name='Tipo da Notificação'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='situacao',
            field=models.IntegerField(choices=[(5, 'Reprovada'), (1, 'Cadastrada'), (3, 'Ativa'), (2, 'Editada'), (4, 'Inativa')], default=1, verbose_name='Situação'),
        ),
    ]
