# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-09 12:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sva', '0002_auto_20180502_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.validate_integer]),
        ),
        migrations.AddField(
            model_name='empresa',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AddField(
            model_name='professor',
            name='telefone',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.validate_integer]),
        ),
    ]
