# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 09:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sva', '0002_auto_20180422_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaga',
            old_name='Gerente_vaga',
            new_name='gerente_vaga',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='gerente_vagas',
        ),
        migrations.AddField(
            model_name='aluno',
            name='areas_atuacao',
            field=models.ManyToManyField(related_name='alunos', to='sva.AreaAtuacao'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaga',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='usuario_aprovacao',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Responsável pela aprovação'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='cidade',
            field=models.CharField(choices=[('LEOPOLDINA', 'Leopoldina'), ('DIVINOPOLIS', 'Divinópolis'), ('ARAXA', 'Araxá'), ('NEPOMUCENO', 'Nepomuceno'), ('VARGINHA', 'Varginha'), ('CURVELO', 'Curvelo'), ('CONTAGEM', 'Contagem'), ('TIMOTEO', 'Timóteo'), ('BELO HORIZONTE', 'Belo Horizonte')], max_length=45),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel_ensino',
            field=models.IntegerField(choices=[(5, 'ESPECIALIZACAO'), (3, 'MESTRADO'), (2, 'GRADUACAO'), (4, 'DOUTORADO'), (1, 'TECNICO')], verbose_name='Nível de Ensino'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Indicação de Vaga'), (5, 'Aprovação de Vaga'), (9, 'Resposta no Fórum'), (7, 'Solicitação de Área de Atuação'), (3, 'Cadastro de Empresa'), (4, 'Cadastro de Vaga'), (8, 'Nova Mensagem no Fórum'), (6, 'Vaga de Interesse'), (2, 'Cadastro de Professor')], verbose_name='Tipo da Notificação'),
        ),
    ]
