# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 09:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sva', '0002_auto_20180422_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='gerente_vagas',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='Gerente_vaga',
        ),
        migrations.AddField(
            model_name='aluno',
            name='areas_atuacao',
            field=models.ManyToManyField(related_name='alunos', to='sva.AreaAtuacao'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professor',
            name='gerentevaga_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sva.GerenteVaga'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaga',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='gerente_vaga',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='sva.GerenteVaga'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='usuario_aprovacao',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Responsável pela aprovação'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='cidade',
            field=models.CharField(choices=[('VARGINHA', 'Varginha'), ('TIMOTEO', 'Timóteo'), ('LEOPOLDINA', 'Leopoldina'), ('NEPOMUCENO', 'Nepomuceno'), ('CURVELO', 'Curvelo'), ('CONTAGEM', 'Contagem'), ('BELO HORIZONTE', 'Belo Horizonte'), ('DIVINOPOLIS', 'Divinópolis'), ('ARAXA', 'Araxá')], max_length=45),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel_ensino',
            field=models.IntegerField(choices=[(2, 'GRADUACAO'), (3, 'MESTRADO'), (1, 'TECNICO'), (5, 'ESPECIALIZACAO'), (4, 'DOUTORADO')], verbose_name='Nível de Ensino'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(5, 'Aprovação de Vaga'), (9, 'Resposta no Fórum'), (6, 'Vaga de Interesse'), (1, 'Indicação de Vaga'), (3, 'Cadastro de Empresa'), (7, 'Solicitação de Área de Atuação'), (8, 'Nova Mensagem no Fórum'), (2, 'Cadastro de Professor'), (4, 'Cadastro de Vaga')], verbose_name='Tipo da Notificação'),
        ),
    ]
