# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-29 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sva', '0002_auto_20180425_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='areaatuacao',
            options={'permissions': (('can_request_area_atuacao', 'Pode solicitar área de atuação'), ('can_release_area_atuacao', 'Pode liberr área de atuaçãos')), 'verbose_name': 'Área de Atuação', 'verbose_name_plural': 'Áreas de Atuação'},
        ),
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name': 'campus', 'verbose_name_plural': 'campi'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='notificacao',
            name='data_leitura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de visualização'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='lida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data da última alteração'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='situacao',
            field=models.IntegerField(choices=[(1, 'Cadastrada'), (3, 'Ativa'), (4, 'Inativa'), (5, 'Reprovada'), (2, 'Editada')], default=1, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sva.Curso'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='cidade',
            field=models.CharField(choices=[('VARGINHA', 'Varginha'), ('ARAXA', 'Araxá'), ('CURVELO', 'Curvelo'), ('TIMOTEO', 'Timóteo'), ('BELO HORIZONTE', 'Belo Horizonte'), ('DIVINOPOLIS', 'Divinópolis'), ('NEPOMUCENO', 'Nepomuceno'), ('LEOPOLDINA', 'Leopoldina'), ('CONTAGEM', 'Contagem')], max_length=45),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel_ensino',
            field=models.IntegerField(choices=[(5, 'ESPECIALIZACAO'), (2, 'GRADUACAO'), (4, 'DOUTORADO'), (3, 'MESTRADO'), (1, 'TECNICO')], verbose_name='Nível de Ensino'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(6, 'Vaga de Interesse'), (5, 'Aprovação de Vaga'), (7, 'Solicitação de Área de Atuação'), (9, 'Resposta no Fórum'), (2, 'Cadastro de Professor'), (8, 'Nova Mensagem no Fórum'), (3, 'Cadastro de Empresa'), (1, 'Indicação de Vaga'), (4, 'Cadastro de Vaga')], verbose_name='Tipo da Notificação'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sva.Curso'),
        ),
        migrations.RenameField(
            model_name='vaga',
            old_name='area_atuacao',
            new_name='areas_atuacao',
        ),
    ]
