# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sva', '0003_auto_20180429_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='alunos_inscritos',
            field=models.ManyToManyField(blank=True, related_name='vagas_inscritas', to='sva.Aluno'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='alunos_interessados',
            field=models.ManyToManyField(blank=True, related_name='vagas_interesse', to='sva.Aluno'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='cidade',
            field=models.CharField(choices=[('VARGINHA', 'Varginha'), ('DIVINOPOLIS', 'Divinópolis'), ('LEOPOLDINA', 'Leopoldina'), ('NEPOMUCENO', 'Nepomuceno'), ('BELO HORIZONTE', 'Belo Horizonte'), ('CONTAGEM', 'Contagem'), ('ARAXA', 'Araxá'), ('TIMOTEO', 'Timóteo'), ('CURVELO', 'Curvelo')], max_length=45),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel_ensino',
            field=models.IntegerField(choices=[(5, 'ESPECIALIZACAO'), (2, 'GRADUACAO'), (1, 'TECNICO'), (3, 'MESTRADO'), (4, 'DOUTORADO')], verbose_name='Nível de Ensino'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(3, 'Cadastro de Empresa'), (4, 'Cadastro de Vaga'), (8, 'Nova Mensagem no Fórum'), (5, 'Aprovação de Vaga'), (7, 'Solicitação de Área de Atuação'), (6, 'Vaga de Interesse'), (1, 'Indicação de Vaga'), (2, 'Cadastro de Professor'), (9, 'Resposta no Fórum')], verbose_name='Tipo da Notificação'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='situacao',
            field=models.IntegerField(choices=[(3, 'Ativa'), (2, 'Editada'), (5, 'Reprovada'), (1, 'Cadastrada'), (4, 'Inativa')], default=1, verbose_name='Situação'),
        ),
    ]
