# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sva', '0003_auto_20180429_2238'),
        ('sva', '0004_auto_20180430_1642'),
    ]

    operations = [
    ]
