# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-26 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sva', '0004_auto_20180517_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to='curriculo/'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='cidade',
            field=models.CharField(choices=[('CURVELO', 'Curvelo'), ('NEPOMUCENO', 'Nepomuceno'), ('LEOPOLDINA', 'Leopoldina'), ('CONTAGEM', 'Contagem'), ('ARAXA', 'Araxá'), ('DIVINOPOLIS', 'Divinópolis'), ('VARGINHA', 'Varginha'), ('BELO HORIZONTE', 'Belo Horizonte'), ('TIMOTEO', 'Timóteo')], max_length=45),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel_ensino',
            field=models.IntegerField(choices=[(5, 'ESPECIALIZACAO'), (3, 'MESTRADO'), (4, 'DOUTORADO'), (1, 'TECNICO'), (2, 'GRADUACAO')], verbose_name='Nível de Ensino'),
        ),
        migrations.AlterField(
            model_name='gerentevaga',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(7, 'Solicitação de Área de Atuação'), (2, 'Cadastro de Professor'), (9, 'Resposta no Fórum'), (3, 'Cadastro de Empresa'), (6, 'Vaga de Interesse'), (8, 'Nova Mensagem no Fórum'), (4, 'Cadastro de Vaga'), (5, 'Aprovação de Vaga'), (1, 'Indicação de Vaga')], verbose_name='Tipo da Notificação'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='situacao',
            field=models.IntegerField(choices=[(4, 'Inativa'), (5, 'Reprovada'), (2, 'Editada'), (1, 'Cadastrada'), (3, 'Ativa')], default=1, verbose_name='Situação'),
        ),
    ]
