# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-28 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sva', '0004_auto_20180517_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerentevaga',
            name='situacao',
            field=models.CharField(choices=[('EXCLUIDO', 'Excluído'), ('INDEFERIDO', 'Indeferido'), ('AGUARDANDO_APROVACAO', 'Aguardando Aprovação'), ('DEFERIDO', 'Deferido')], default='AGUARDANDO_APROVACAO', max_length=30, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='cidade',
            field=models.CharField(choices=[('NEPOMUCENO', 'Nepomuceno'), ('LEOPOLDINA', 'Leopoldina'), ('DIVINOPOLIS', 'Divinópolis'), ('VARGINHA', 'Varginha'), ('BELO HORIZONTE', 'Belo Horizonte'), ('CONTAGEM', 'Contagem'), ('TIMOTEO', 'Timóteo'), ('CURVELO', 'Curvelo'), ('ARAXA', 'Araxá')], max_length=45),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel_ensino',
            field=models.IntegerField(choices=[(4, 'DOUTORADO'), (1, 'TECNICO'), (3, 'MESTRADO'), (5, 'ESPECIALIZACAO'), (2, 'GRADUACAO')], verbose_name='Nível de Ensino'),
        ),
        migrations.AlterField(
            model_name='gerentevaga',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Indicação de Vaga'), (7, 'Solicitação de Área de Atuação'), (3, 'Cadastro de Empresa'), (8, 'Nova Mensagem no Fórum'), (4, 'Cadastro de Vaga'), (9, 'Resposta no Fórum'), (2, 'Cadastro de Professor'), (5, 'Aprovação de Vaga'), (6, 'Vaga de Interesse')], verbose_name='Tipo da Notificação'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='situacao',
            field=models.IntegerField(choices=[(2, 'Editada'), (4, 'Inativa'), (3, 'Ativa'), (1, 'Cadastrada'), (5, 'Reprovada')], default=1, verbose_name='Situação'),
        ),
    ]
