# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-27 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sva', '0004_auto_20180517_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to='curriculo/'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_upload_curriculo',
            field=models.DateTimeField(null=True, verbose_name='Data de upload'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='cidade',
            field=models.CharField(choices=[('CURVELO', 'Curvelo'), ('LEOPOLDINA', 'Leopoldina'), ('BELO HORIZONTE', 'Belo Horizonte'), ('TIMOTEO', 'Timóteo'), ('CONTAGEM', 'Contagem'), ('ARAXA', 'Araxá'), ('DIVINOPOLIS', 'Divinópolis'), ('VARGINHA', 'Varginha'), ('NEPOMUCENO', 'Nepomuceno')], max_length=45),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel_ensino',
            field=models.IntegerField(choices=[(2, 'GRADUACAO'), (1, 'TECNICO'), (4, 'DOUTORADO'), (5, 'ESPECIALIZACAO'), (3, 'MESTRADO')], verbose_name='Nível de Ensino'),
        ),
        migrations.AlterField(
            model_name='gerentevaga',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(9, 'Resposta no Fórum'), (8, 'Nova Mensagem no Fórum'), (1, 'Indicação de Vaga'), (4, 'Cadastro de Vaga'), (7, 'Solicitação de Área de Atuação'), (3, 'Cadastro de Empresa'), (5, 'Aprovação de Vaga'), (6, 'Vaga de Interesse'), (2, 'Cadastro de Professor')], verbose_name='Tipo da Notificação'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='situacao',
            field=models.IntegerField(choices=[(3, 'Ativa'), (2, 'Editada'), (5, 'Reprovada'), (1, 'Cadastrada'), (4, 'Inativa')], default=1, verbose_name='Situação'),
        ),
    ]
