# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-08 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sva', '0005_auto_20180528_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='campus',
            name='cidade',
            field=models.CharField(choices=[('BELO HORIZONTE', 'Belo Horizonte'), ('DIVINOPOLIS', 'Divinópolis'), ('CURVELO', 'Curvelo'), ('VARGINHA', 'Varginha'), ('ARAXA', 'Araxá'), ('LEOPOLDINA', 'Leopoldina'), ('NEPOMUCENO', 'Nepomuceno'), ('TIMOTEO', 'Timóteo'), ('CONTAGEM', 'Contagem')], max_length=45),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel_ensino',
            field=models.IntegerField(choices=[(4, 'DOUTORADO'), (5, 'ESPECIALIZACAO'), (3, 'MESTRADO'), (1, 'TECNICO'), (2, 'GRADUACAO')], verbose_name='Nível de Ensino'),
        ),
        migrations.AlterField(
            model_name='gerentevaga',
            name='situacao',
            field=models.CharField(choices=[('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido'), ('EXCLUIDO', 'Excluído'), ('AGUARDANDO_APROVACAO', 'Aguardando Aprovação')], default='AGUARDANDO_APROVACAO', max_length=30, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(4, 'Cadastro de Vaga'), (7, 'Solicitação de Área de Atuação'), (9, 'Resposta no Fórum'), (10, 'Vaga Reprovada'), (11, 'Novos Candidatos'), (1, 'Indicação de Vaga'), (6, 'Vaga de Interesse'), (8, 'Nova Mensagem no Fórum'), (3, 'Cadastro de Empresa'), (5, 'Aprovação de Vaga'), (2, 'Cadastro de Professor')], verbose_name='Tipo da Notificação'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='situacao',
            field=models.IntegerField(choices=[(1, 'Cadastrada'), (5, 'Reprovada'), (4, 'Inativa'), (2, 'Editada'), (3, 'Ativa')], default=1, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='tipo_vaga',
            field=models.IntegerField(choices=[(3, 'Iniciação Científica'), (1, 'Estágio'), (4, 'Outro'), (2, 'Monitoria')], default=4, verbose_name='Tipo da Vaga'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='vaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='sva.Vaga'),
        ),
    ]
