# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-11 00:05
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sva', '0006_auto_20180608_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveIntegerField(choices=[(2, 'Nome de vagas'), (7, 'Local'), (3, 'Gerentes e/ou professores'), (6, 'Descrição'), (1, 'Todos os campos'), (5, 'Cursos'), (4, 'Áreas de atuação')], default=1, verbose_name='Tipo do filtro')),
                ('texto', models.TextField(blank=True, max_length=255, null=True)),
                ('areas_atuacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filtro', to='sva.AreaAtuacao')),
            ],
            options={
                'verbose_name': 'Filtro',
                'verbose_name_plural': 'Filtros',
            },
        ),
        migrations.RemoveField(
            model_name='filtropesquisa',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='filtropesquisa',
            name='chave',
        ),
        migrations.RemoveField(
            model_name='filtropesquisa',
            name='valor',
        ),
        migrations.AddField(
            model_name='filtropesquisa',
            name='avaliacao',
            field=models.IntegerField(choices=[(2, 'Duas estrelas'), (1, 'Uma estrela'), (3, 'Três estrelas'), (4, 'Quatro estrelas'), (5, 'Cinco estrelas'), (0, 'Nenhuma avaliação')], default=0, verbose_name='Avaliação das vagas'),
        ),
        migrations.AddField(
            model_name='filtropesquisa',
            name='carga_horaria_maxima',
            field=models.PositiveIntegerField(default=45, validators=[django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z', 32), code='invalid', message='Enter a valid integer.')], verbose_name='Carga horária semanal máxima'),
        ),
        migrations.AddField(
            model_name='filtropesquisa',
            name='carga_horaria_minima',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z', 32), code='invalid', message='Enter a valid integer.')], verbose_name='Carga horária semanal mínima'),
        ),
        migrations.AddField(
            model_name='filtropesquisa',
            name='nivel',
            field=models.PositiveIntegerField(choices=[(2, 'Graduação'), (1, 'Técnico'), (4, 'Doutorado'), (5, 'Especialização'), (3, 'Mestrado')], null=True, verbose_name='Situação das vagas'),
        ),
        migrations.AddField(
            model_name='filtropesquisa',
            name='ordenacao',
            field=models.PositiveIntegerField(choices=[(2, 'Mais inscritas'), (1, 'Mais recentes'), (3, 'Melhores avaliações'), (5, 'Menor prazo de inscrição'), (4, 'Mais comentadas')], default=1, verbose_name='Forma de ordenação dos resultados'),
        ),
        migrations.AddField(
            model_name='filtropesquisa',
            name='salario',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor salarial'),
        ),
        migrations.AddField(
            model_name='filtropesquisa',
            name='situacao',
            field=models.PositiveIntegerField(choices=[(5, 'Todas'), (3, 'Inativas'), (2, 'Pendentes de avaliação'), (4, 'Reprovadas'), (1, 'Ativas')], default=1, verbose_name='Situação das vagas'),
        ),
        migrations.AddField(
            model_name='filtropesquisa',
            name='tipo_estagio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filtropesquisa',
            name='tipo_ic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filtropesquisa',
            name='tipo_monitoria',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filtropesquisa',
            name='tipo_outros',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filtropesquisa',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filtro_pesquisa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campus',
            name='cidade',
            field=models.CharField(choices=[('CONTAGEM', 'Contagem'), ('TIMOTEO', 'Timóteo'), ('CURVELO', 'Curvelo'), ('BELO HORIZONTE', 'Belo Horizonte'), ('VARGINHA', 'Varginha'), ('NEPOMUCENO', 'Nepomuceno'), ('LEOPOLDINA', 'Leopoldina'), ('DIVINOPOLIS', 'Divinópolis'), ('ARAXA', 'Araxá')], max_length=45),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel_ensino',
            field=models.IntegerField(choices=[(4, 'DOUTORADO'), (2, 'GRADUACAO'), (5, 'ESPECIALIZACAO'), (3, 'MESTRADO'), (1, 'TECNICO')], verbose_name='Nível de Ensino'),
        ),
        migrations.AlterField(
            model_name='gerentevaga',
            name='situacao',
            field=models.CharField(choices=[('AGUARDANDO_APROVACAO', 'Aguardando Aprovação'), ('INDEFERIDO', 'Indeferido'), ('DEFERIDO', 'Deferido'), ('EXCLUIDO', 'Excluído')], default='AGUARDANDO_APROVACAO', max_length=30, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Indicação de Vaga'), (4, 'Cadastro de Vaga'), (5, 'Aprovação de Vaga'), (11, 'Novos Candidatos'), (7, 'Solicitação de Área de Atuação'), (3, 'Cadastro de Empresa'), (2, 'Cadastro de Professor'), (8, 'Nova Mensagem no Fórum'), (10, 'Vaga Reprovada'), (9, 'Resposta no Fórum'), (6, 'Vaga de Interesse')], verbose_name='Tipo da Notificação'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='situacao',
            field=models.IntegerField(choices=[(4, 'Inativa'), (2, 'Editada'), (3, 'Ativa'), (5, 'Reprovada'), (1, 'Cadastrada')], default=1, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='tipo_vaga',
            field=models.IntegerField(choices=[(1, 'Estágio'), (4, 'Outro'), (3, 'Iniciação Científica'), (2, 'Monitoria')], default=4, verbose_name='Tipo da Vaga'),
        ),
        migrations.AddField(
            model_name='filtro',
            name='cursos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filtro', to='sva.Curso'),
        ),
        migrations.AddField(
            model_name='filtropesquisa',
            name='filtros',
            field=models.ManyToManyField(related_name='pesquisa', to='sva.Filtro'),
        ),
    ]
