# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-12 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sva', '0007_auto_20180611_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaatuacao',
            name='situacao',
            field=models.CharField(choices=[('DEFERIDO', 'Deferido'), ('AGUARDANDO_APROVACAO', 'Aguardando Aprovação')], default='AGUARDANDO_APROVACAO', max_length=30, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='cidade',
            field=models.CharField(choices=[('VARGINHA', 'Varginha'), ('CONTAGEM', 'Contagem'), ('ARAXA', 'Araxá'), ('DIVINOPOLIS', 'Divinópolis'), ('TIMOTEO', 'Timóteo'), ('BELO HORIZONTE', 'Belo Horizonte'), ('LEOPOLDINA', 'Leopoldina'), ('CURVELO', 'Curvelo'), ('NEPOMUCENO', 'Nepomuceno')], max_length=45),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel_ensino',
            field=models.IntegerField(choices=[(4, 'DOUTORADO'), (5, 'ESPECIALIZACAO'), (1, 'TECNICO'), (2, 'GRADUACAO'), (3, 'MESTRADO')], verbose_name='Nível de Ensino'),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(5, 'Cursos'), (1, 'Todos os campos'), (3, 'Gerentes e/ou professores'), (4, 'Áreas de atuação'), (2, 'Nome de vagas'), (6, 'Descrição'), (7, 'Local')], default=1, verbose_name='Tipo do filtro'),
        ),
        migrations.AlterField(
            model_name='filtropesquisa',
            name='avaliacao',
            field=models.IntegerField(choices=[(2, 'Duas estrelas'), (4, 'Quatro estrelas'), (0, 'Nenhuma avaliação'), (1, 'Uma estrela'), (5, 'Cinco estrelas'), (3, 'Três estrelas')], default=0, verbose_name='Avaliação das vagas'),
        ),
        migrations.AlterField(
            model_name='filtropesquisa',
            name='nivel',
            field=models.PositiveIntegerField(choices=[(2, 'Graduação'), (3, 'Mestrado'), (1, 'Técnico'), (5, 'Especialização'), (4, 'Doutorado'), (0, 'Qualquer')], null=True, verbose_name='Situação das vagas'),
        ),
        migrations.AlterField(
            model_name='filtropesquisa',
            name='ordenacao',
            field=models.PositiveIntegerField(choices=[(2, 'Mais inscritas'), (4, 'Mais comentadas'), (3, 'Melhores avaliações'), (5, 'Menor prazo de inscrição'), (1, 'Mais recentes')], default=1, verbose_name='Forma de ordenação dos resultados'),
        ),
        migrations.AlterField(
            model_name='filtropesquisa',
            name='situacao',
            field=models.PositiveIntegerField(choices=[(2, 'Pendentes de avaliação'), (5, 'Todas'), (3, 'Inativas'), (4, 'Reprovadas'), (1, 'Ativas')], default=1, verbose_name='Situação das vagas'),
        ),
        migrations.AlterField(
            model_name='gerentevaga',
            name='situacao',
            field=models.CharField(choices=[('EXCLUIDO', 'Excluído'), ('DEFERIDO', 'Deferido'), ('AGUARDANDO_APROVACAO', 'Aguardando Aprovação'), ('INDEFERIDO', 'Indeferido')], default='AGUARDANDO_APROVACAO', max_length=30, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(9, 'Resposta no Fórum'), (10, 'Vaga Reprovada'), (11, 'Novos Candidatos'), (1, 'Indicação de Vaga'), (3, 'Cadastro de Empresa'), (5, 'Aprovação de Vaga'), (4, 'Cadastro de Vaga'), (2, 'Cadastro de Professor'), (7, 'Solicitação de Área de Atuação'), (8, 'Nova Mensagem no Fórum'), (6, 'Vaga de Interesse')], verbose_name='Tipo da Notificação'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='situacao',
            field=models.IntegerField(choices=[(2, 'Editada'), (1, 'Cadastrada'), (5, 'Reprovada'), (3, 'Ativa'), (4, 'Inativa')], default=1, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='tipo_vaga',
            field=models.IntegerField(choices=[(2, 'Monitoria'), (1, 'Estágio'), (4, 'Outro'), (3, 'Iniciação Científica')], default=4, verbose_name='Tipo da Vaga'),
        ),
    ]
